name: Alif Type
title: حروف ألف
description: مسبك حروف رقمي
url: https://aliftype.com
baseurl: ""
google_analytics: G-3DGD02NENY
repository: aliftype/aliftype.github.io

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-github-metadata
exclude:
  - app/harfbuzz

defaults:
  - scope: { path: amiri }
    values: { layout: font }
  - scope: { path: astrolabe }
    values: { layout: font }
  - scope: { path: qahiri }
    values: { layout: font }
  - scope: { path: qashib }
    values: { layout: font }
  - scope: { path: rana-kufi }
    values: { layout: font }
  - scope: { path: raqq }
    values: { layout: font }
