amiri:
  name: Amiri
  version: "1.000"
  title: أميري
  subtitle: خط عربي للمتون
  title-separator: "\u200A—\u200A"
  app: False
  artwork: False

raqq:
  name: Raqq
  version: "2.00"
  title: رَقّ
  subtitle: كُوفِي المَصاحفِ الأولَى
  title-separator: "\u200A۝\u200A"
  app: False
  artwork: True

qahiri:
  name: Qahiri
  version: "3.00"
  title: قاهري
  subtitle: خط كوفي مصحفي
  title-separator: "—"
  app: True
  artwork: False

rana-kufi:
  name: Rana Kufi
  version: "0.4"
  title: كوفي رنا
  subtitle: خط كوفي فاطمي
  title-separator: "\u200A۝\u200A"
  app: True
  artwork: False
