amiri:
  name: Amiri
  version: "1.000"
  title: أميري
  subtitle: خط عربي للمتون
  title-separator: "\u200A—\u200A"
  app: False

raqq:
  name: Raqq
  version: "2.00"
  title: رَقّ
  subtitle: كُوفِي المَصاحفِ الأولَى
  title-separator: "\u200A۝\u200A"
  app: False

qahiri:
  name: Qahiri
  version: "3.00"
  title: قاهري
  subtitle: خط كوفي مصحفي
  title-separator: "—"
  app:
    toolbar: [onum, round-dots, remove-dots]

rana-kufi:
  name: Rana Kufi
  version: "0.4"
  title: كوفي رنا
  subtitle: خط كوفي فاطمي
  title-separator: "\u200A۝\u200A"
  app:
    toolbar: [remove-dots, nocolor-dots, small-dots, adjust-dots]
